"""add large column add orderbook socket

Revision ID: 179c26e15342
Revises: e9cd917e3023
Create Date: 2018-05-08 06:30:26.048900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179c26e15342'
down_revision = 'e9cd917e3023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderbook', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook', 'id')
    # ### end Alembic commands ###
