"""add orders

Revision ID: 27f95c555aff
Revises: 3664b3da04af
Create Date: 2018-05-06 20:49:21.713109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27f95c555aff'
down_revision = '3664b3da04af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderbook',
    sa.Column('cur_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderbook', sa.String(length=1), nullable=True),
    sa.Column('bid_ask', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('cur_id', 'id')
    )
    op.add_column('trade', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('sell_buy', sa.Boolean(), nullable=True))
    op.add_column('trade', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('trade', sa.Column('trade', sa.String(length=1), nullable=True))
    op.drop_column('trade', 'quantity')
    op.drop_column('trade', 'book')
    op.drop_column('trade', 'type')
    op.drop_column('trade', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('type', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('book', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('trade', 'trade')
    op.drop_column('trade', 'timestamp')
    op.drop_column('trade', 'sell_buy')
    op.drop_column('trade', 'amount')
    op.drop_table('orderbook')
    # ### end Alembic commands ###
