"""change sell-buy to string

Revision ID: e767fae8d3af
Revises: 27f95c555aff
Create Date: 2018-05-07 06:20:45.703154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e767fae8d3af'
down_revision = '27f95c555aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('type', sa.String(length=5), nullable=True))
    op.drop_column('trade', 'sell_buy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('sell_buy', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('trade', 'type')
    # ### end Alembic commands ###
