"""add large column add orderbook socket

Revision ID: e9cd917e3023
Revises: 736a30c7528a
Create Date: 2018-05-08 06:12:42.696863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cd917e3023'
down_revision = '736a30c7528a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderbook', 'id')
    op.add_column('trade', sa.Column('large', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'large')
    op.add_column('orderbook', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
