"""remove unneeded tables

Revision ID: ff9bc788b1e1
Revises: fffc6ee85cec
Create Date: 2018-05-10 06:27:07.427488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff9bc788b1e1'
down_revision = 'fffc6ee85cec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rest_trade')
    op.drop_table('large_trade')
    op.drop_table('orderbook')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderbook',
    sa.Column('cur_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderbook', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('bid_ask', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_table('large_trade',
    sa.Column('trade', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'threshold', 'book', name='large_trade_pkey')
    )
    op.create_table('rest_trade',
    sa.Column('globalTradeID', sa.INTEGER(), server_default=sa.text('nextval(\'"rest_trade_globalTradeID_seq"\'::regclass)'), nullable=False),
    sa.Column('book', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('tradeID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('globalTradeID', name='rest_trade_pkey')
    )
    # ### end Alembic commands ###
